# Generated by Django 4.2.23 on 2025-06-23 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('researcher', 'Chercheur'), ('data_scientist', 'Data Scientist')], max_length=20)),
                ('expertise', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('expert', 'Expert')], max_length=20)),
                ('domain', models.CharField(choices=[('health', 'Santé'), ('finance', 'Finance'), ('education', 'Éducation')], max_length=20)),
                ('visual_pref', models.CharField(choices=[('graph', 'Graphes'), ('table', 'Tableaux'), ('text', 'Texte explicatif')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
