# Generated by Django 4.2.23 on 2025-06-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('random_forest', 'Random Forest'), ('deep_learning', 'Deep Learning'), ('svm', 'SVM'), ('logistic_regression', 'Logistic Regression')], max_length=50)),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Régression')], max_length=50)),
                ('data_type', models.CharField(choices=[('images', 'Images'), ('text', 'Texte'), ('tabular', 'Tabulaires')], max_length=50)),
                ('person_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_context', to='userInfos.personprofile')),
            ],
        ),
    ]
