# Generated by Django 4.2.23 on 2025-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfos', '0002_technicalcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='domain',
            field=models.CharField(choices=[('health', 'Santé'), ('math', 'Mathématiques'), ('info', 'informatique'), ('finance', 'Finance'), ('education', 'Éducation'), ('secondaire', 'Éducation secondaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='expertise',
            field=models.CharField(choices=[('0', 'Débutant'), ('1', 'Intermédiaire'), ('2', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='role',
            field=models.CharField(choices=[('S', 'Étudiant'), ('C', 'Chercheur'), ('P', 'Professeur'), ('D', 'Data Scientist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='technicalcontext',
            name='data_type',
            field=models.CharField(choices=[('img', 'Images'), ('txt', 'Texte'), ('tab', 'Tabulaires')], max_length=50),
        ),
        migrations.AlterField(
            model_name='technicalcontext',
            name='model_type',
            field=models.CharField(choices=[('RF', 'Random Forest'), ('DL', 'Deep Learning'), ('svm', 'SVM'), ('LR', 'Logistic Regression')], max_length=50),
        ),
        migrations.AlterField(
            model_name='technicalcontext',
            name='task_type',
            field=models.CharField(choices=[('C', 'Classification'), ('R', 'Régression')], max_length=50),
        ),
    ]
