# Generated by Django 4.2.23 on 2025-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfos', '0003_alter_personprofile_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='domain',
            field=models.CharField(choices=[('health', 'Santé'), ('math', 'Mathématiques'), ('info', 'Informatique'), ('finance', 'Finance'), ('education', 'Éducation'), ('secondaire', 'Éducation secondaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='expertise',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='role',
            field=models.CharField(choices=[('étudiant', 'Étudiant'), ('chercheur', 'Chercheur'), ('professeur', 'Professeur'), ('Data Scientist', 'Data Scientist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='visual_pref',
            field=models.CharField(choices=[('graph', 'Graphes'), ('table', 'Tableaux'), ('texte', 'Texte explicatif')], max_length=20),
        ),
    ]
