# Generated by Django 4.2.23 on 2025-07-10 14:00

from django.db import migrations, models
import userInfos.models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfos', '0004_alter_personprofile_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explainer', models.CharField(choices=[(userInfos.models.Recommendation.Explainer['LIME'], 'LIME'), (userInfos.models.Recommendation.Explainer['SHAP'], 'SHAP'), (userInfos.models.Recommendation.Explainer['PFI'], 'Permutation Feature Importance (PFI)'), (userInfos.models.Recommendation.Explainer['ANCHOR'], 'Anchor')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TechnicalContext',
        ),
    ]
