# Generated by Django 4.2.23 on 2025-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Régression')], max_length=20)),
                ('explainer', models.CharField(choices=[('lime', 'LIME'), ('shap', 'SHAP'), ('PFI', 'Permutation Feature Importance (PFI)'), ('anchor', 'Anchor'), ('IG', 'Integrated Gradients'), ('GC', 'Grad-CAM'), ('CE', 'CounterFactual Explainations'), ('SM', 'Surrogate Models'), ('DL', 'DeepLIFT')], max_length=20)),
            ],
        ),
    ]
