# Generated by Django 4.2.23 on 2025-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xAI_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='explainer',
            field=models.CharField(choices=[('LIME', 'LIME'), ('SHAP', 'SHAP'), ('PFI', 'Permutation Feature Importance (PFI)'), ('ANCHOR', 'Anchor'), ('INTEGRATED_GRADIENTS', 'Integrated Gradients'), ('GRAD_CAM', 'Grad-CAM'), ('COUNTERFACTUAL', 'CounterFactual Explainations'), ('SURROGATE', 'Surrogate Models'), ('DEEP_LIFT', 'DeepLIFT')], max_length=30),
        ),
    ]
